// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: gosight/events.proto

package gosight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event type enum
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED       EventType = 0
	EventType_EVENT_TYPE_PAGE_VIEW         EventType = 1
	EventType_EVENT_TYPE_CLICK             EventType = 2
	EventType_EVENT_TYPE_SCROLL            EventType = 3
	EventType_EVENT_TYPE_INPUT_CHANGE      EventType = 4
	EventType_EVENT_TYPE_INPUT_FOCUS       EventType = 5
	EventType_EVENT_TYPE_INPUT_BLUR        EventType = 6
	EventType_EVENT_TYPE_MOUSE_MOVE        EventType = 7
	EventType_EVENT_TYPE_VISIBILITY_CHANGE EventType = 8
	EventType_EVENT_TYPE_JS_ERROR          EventType = 9
	EventType_EVENT_TYPE_NETWORK_ERROR     EventType = 10
	EventType_EVENT_TYPE_CONSOLE_LOG       EventType = 11
	EventType_EVENT_TYPE_WEB_VITALS        EventType = 12
	EventType_EVENT_TYPE_PAGE_LOAD         EventType = 13
	EventType_EVENT_TYPE_RESOURCE_LOAD     EventType = 14
	EventType_EVENT_TYPE_CUSTOM            EventType = 15
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_PAGE_VIEW",
		2:  "EVENT_TYPE_CLICK",
		3:  "EVENT_TYPE_SCROLL",
		4:  "EVENT_TYPE_INPUT_CHANGE",
		5:  "EVENT_TYPE_INPUT_FOCUS",
		6:  "EVENT_TYPE_INPUT_BLUR",
		7:  "EVENT_TYPE_MOUSE_MOVE",
		8:  "EVENT_TYPE_VISIBILITY_CHANGE",
		9:  "EVENT_TYPE_JS_ERROR",
		10: "EVENT_TYPE_NETWORK_ERROR",
		11: "EVENT_TYPE_CONSOLE_LOG",
		12: "EVENT_TYPE_WEB_VITALS",
		13: "EVENT_TYPE_PAGE_LOAD",
		14: "EVENT_TYPE_RESOURCE_LOAD",
		15: "EVENT_TYPE_CUSTOM",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":       0,
		"EVENT_TYPE_PAGE_VIEW":         1,
		"EVENT_TYPE_CLICK":             2,
		"EVENT_TYPE_SCROLL":            3,
		"EVENT_TYPE_INPUT_CHANGE":      4,
		"EVENT_TYPE_INPUT_FOCUS":       5,
		"EVENT_TYPE_INPUT_BLUR":        6,
		"EVENT_TYPE_MOUSE_MOVE":        7,
		"EVENT_TYPE_VISIBILITY_CHANGE": 8,
		"EVENT_TYPE_JS_ERROR":          9,
		"EVENT_TYPE_NETWORK_ERROR":     10,
		"EVENT_TYPE_CONSOLE_LOG":       11,
		"EVENT_TYPE_WEB_VITALS":        12,
		"EVENT_TYPE_PAGE_LOAD":         13,
		"EVENT_TYPE_RESOURCE_LOAD":     14,
		"EVENT_TYPE_CUSTOM":            15,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_gosight_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_gosight_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{0}
}

// Base event
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type      EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=gosight.EventType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix milliseconds
	Page      *Page                  `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Click
	//	*Event_Scroll
	//	*Event_Input
	//	*Event_MouseMove
	//	*Event_JsError
	//	*Event_WebVitals
	//	*Event_PageLoad
	//	*Event_Custom
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_gosight_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetClick() *ClickEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Click); ok {
			return x.Click
		}
	}
	return nil
}

func (x *Event) GetScroll() *ScrollEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Scroll); ok {
			return x.Scroll
		}
	}
	return nil
}

func (x *Event) GetInput() *InputEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *Event) GetMouseMove() *MouseMoveEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_MouseMove); ok {
			return x.MouseMove
		}
	}
	return nil
}

func (x *Event) GetJsError() *JsErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_JsError); ok {
			return x.JsError
		}
	}
	return nil
}

func (x *Event) GetWebVitals() *WebVitalsEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_WebVitals); ok {
			return x.WebVitals
		}
	}
	return nil
}

func (x *Event) GetPageLoad() *PageLoadEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_PageLoad); ok {
			return x.PageLoad
		}
	}
	return nil
}

func (x *Event) GetCustom() *CustomEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Click struct {
	Click *ClickEvent `protobuf:"bytes,10,opt,name=click,proto3,oneof"`
}

type Event_Scroll struct {
	Scroll *ScrollEvent `protobuf:"bytes,11,opt,name=scroll,proto3,oneof"`
}

type Event_Input struct {
	Input *InputEvent `protobuf:"bytes,12,opt,name=input,proto3,oneof"`
}

type Event_MouseMove struct {
	MouseMove *MouseMoveEvent `protobuf:"bytes,13,opt,name=mouse_move,json=mouseMove,proto3,oneof"`
}

type Event_JsError struct {
	JsError *JsErrorEvent `protobuf:"bytes,14,opt,name=js_error,json=jsError,proto3,oneof"`
}

type Event_WebVitals struct {
	WebVitals *WebVitalsEvent `protobuf:"bytes,15,opt,name=web_vitals,json=webVitals,proto3,oneof"`
}

type Event_PageLoad struct {
	PageLoad *PageLoadEvent `protobuf:"bytes,16,opt,name=page_load,json=pageLoad,proto3,oneof"`
}

type Event_Custom struct {
	Custom *CustomEvent `protobuf:"bytes,17,opt,name=custom,proto3,oneof"`
}

func (*Event_Click) isEvent_Payload() {}

func (*Event_Scroll) isEvent_Payload() {}

func (*Event_Input) isEvent_Payload() {}

func (*Event_MouseMove) isEvent_Payload() {}

func (*Event_JsError) isEvent_Payload() {}

func (*Event_WebVitals) isEvent_Payload() {}

func (*Event_PageLoad) isEvent_Payload() {}

func (*Event_Custom) isEvent_Payload() {}

// Click event payload
type ClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Target        *TargetElement         `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_gosight_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{1}
}

func (x *ClickEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClickEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClickEvent) GetTarget() *TargetElement {
	if x != nil {
		return x.Target
	}
	return nil
}

// Scroll event payload
type ScrollEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScrollTop      int32                  `protobuf:"varint,1,opt,name=scroll_top,json=scrollTop,proto3" json:"scroll_top,omitempty"`
	ScrollHeight   int32                  `protobuf:"varint,2,opt,name=scroll_height,json=scrollHeight,proto3" json:"scroll_height,omitempty"`
	ViewportHeight int32                  `protobuf:"varint,3,opt,name=viewport_height,json=viewportHeight,proto3" json:"viewport_height,omitempty"`
	DepthPercent   int32                  `protobuf:"varint,4,opt,name=depth_percent,json=depthPercent,proto3" json:"depth_percent,omitempty"` // 0-100
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScrollEvent) Reset() {
	*x = ScrollEvent{}
	mi := &file_gosight_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollEvent) ProtoMessage() {}

func (x *ScrollEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollEvent.ProtoReflect.Descriptor instead.
func (*ScrollEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{2}
}

func (x *ScrollEvent) GetScrollTop() int32 {
	if x != nil {
		return x.ScrollTop
	}
	return 0
}

func (x *ScrollEvent) GetScrollHeight() int32 {
	if x != nil {
		return x.ScrollHeight
	}
	return 0
}

func (x *ScrollEvent) GetViewportHeight() int32 {
	if x != nil {
		return x.ViewportHeight
	}
	return 0
}

func (x *ScrollEvent) GetDepthPercent() int32 {
	if x != nil {
		return x.DepthPercent
	}
	return 0
}

// Input event payload
type InputEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *TargetElement         `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	InputType     string                 `protobuf:"bytes,2,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	IsMasked      bool                   `protobuf:"varint,3,opt,name=is_masked,json=isMasked,proto3" json:"is_masked,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // only if not masked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputEvent) Reset() {
	*x = InputEvent{}
	mi := &file_gosight_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEvent) ProtoMessage() {}

func (x *InputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEvent.ProtoReflect.Descriptor instead.
func (*InputEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{3}
}

func (x *InputEvent) GetTarget() *TargetElement {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InputEvent) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *InputEvent) GetIsMasked() bool {
	if x != nil {
		return x.IsMasked
	}
	return false
}

func (x *InputEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Mouse move event (batched positions)
type MouseMoveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*MousePosition       `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseMoveEvent) Reset() {
	*x = MouseMoveEvent{}
	mi := &file_gosight_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseMoveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseMoveEvent) ProtoMessage() {}

func (x *MouseMoveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseMoveEvent.ProtoReflect.Descriptor instead.
func (*MouseMoveEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{4}
}

func (x *MouseMoveEvent) GetPositions() []*MousePosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type MousePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	T             int64                  `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"` // relative timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MousePosition) Reset() {
	*x = MousePosition{}
	mi := &file_gosight_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MousePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MousePosition) ProtoMessage() {}

func (x *MousePosition) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MousePosition.ProtoReflect.Descriptor instead.
func (*MousePosition) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{5}
}

func (x *MousePosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MousePosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MousePosition) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

// JavaScript error
type JsErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Stack         string                 `protobuf:"bytes,2,opt,name=stack,proto3" json:"stack,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	ErrorType     string                 `protobuf:"bytes,6,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsErrorEvent) Reset() {
	*x = JsErrorEvent{}
	mi := &file_gosight_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsErrorEvent) ProtoMessage() {}

func (x *JsErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsErrorEvent.ProtoReflect.Descriptor instead.
func (*JsErrorEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{6}
}

func (x *JsErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsErrorEvent) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *JsErrorEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *JsErrorEvent) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *JsErrorEvent) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *JsErrorEvent) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

// Web vitals metrics
type WebVitalsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lcp           *float64               `protobuf:"fixed64,1,opt,name=lcp,proto3,oneof" json:"lcp,omitempty"`   // Largest Contentful Paint
	Fid           *float64               `protobuf:"fixed64,2,opt,name=fid,proto3,oneof" json:"fid,omitempty"`   // First Input Delay
	Cls           *float64               `protobuf:"fixed64,3,opt,name=cls,proto3,oneof" json:"cls,omitempty"`   // Cumulative Layout Shift
	Ttfb          *float64               `protobuf:"fixed64,4,opt,name=ttfb,proto3,oneof" json:"ttfb,omitempty"` // Time to First Byte
	Fcp           *float64               `protobuf:"fixed64,5,opt,name=fcp,proto3,oneof" json:"fcp,omitempty"`   // First Contentful Paint
	Inp           *float64               `protobuf:"fixed64,6,opt,name=inp,proto3,oneof" json:"inp,omitempty"`   // Interaction to Next Paint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebVitalsEvent) Reset() {
	*x = WebVitalsEvent{}
	mi := &file_gosight_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebVitalsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebVitalsEvent) ProtoMessage() {}

func (x *WebVitalsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebVitalsEvent.ProtoReflect.Descriptor instead.
func (*WebVitalsEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{7}
}

func (x *WebVitalsEvent) GetLcp() float64 {
	if x != nil && x.Lcp != nil {
		return *x.Lcp
	}
	return 0
}

func (x *WebVitalsEvent) GetFid() float64 {
	if x != nil && x.Fid != nil {
		return *x.Fid
	}
	return 0
}

func (x *WebVitalsEvent) GetCls() float64 {
	if x != nil && x.Cls != nil {
		return *x.Cls
	}
	return 0
}

func (x *WebVitalsEvent) GetTtfb() float64 {
	if x != nil && x.Ttfb != nil {
		return *x.Ttfb
	}
	return 0
}

func (x *WebVitalsEvent) GetFcp() float64 {
	if x != nil && x.Fcp != nil {
		return *x.Fcp
	}
	return 0
}

func (x *WebVitalsEvent) GetInp() float64 {
	if x != nil && x.Inp != nil {
		return *x.Inp
	}
	return 0
}

// Page load timing
type PageLoadEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DnsLookup      int64                  `protobuf:"varint,1,opt,name=dns_lookup,json=dnsLookup,proto3" json:"dns_lookup,omitempty"`
	TcpConnect     int64                  `protobuf:"varint,2,opt,name=tcp_connect,json=tcpConnect,proto3" json:"tcp_connect,omitempty"`
	RequestStart   int64                  `protobuf:"varint,3,opt,name=request_start,json=requestStart,proto3" json:"request_start,omitempty"`
	ResponseStart  int64                  `protobuf:"varint,4,opt,name=response_start,json=responseStart,proto3" json:"response_start,omitempty"`
	ResponseEnd    int64                  `protobuf:"varint,5,opt,name=response_end,json=responseEnd,proto3" json:"response_end,omitempty"`
	DomInteractive int64                  `protobuf:"varint,6,opt,name=dom_interactive,json=domInteractive,proto3" json:"dom_interactive,omitempty"`
	DomComplete    int64                  `protobuf:"varint,7,opt,name=dom_complete,json=domComplete,proto3" json:"dom_complete,omitempty"`
	LoadComplete   int64                  `protobuf:"varint,8,opt,name=load_complete,json=loadComplete,proto3" json:"load_complete,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PageLoadEvent) Reset() {
	*x = PageLoadEvent{}
	mi := &file_gosight_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageLoadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageLoadEvent) ProtoMessage() {}

func (x *PageLoadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageLoadEvent.ProtoReflect.Descriptor instead.
func (*PageLoadEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{8}
}

func (x *PageLoadEvent) GetDnsLookup() int64 {
	if x != nil {
		return x.DnsLookup
	}
	return 0
}

func (x *PageLoadEvent) GetTcpConnect() int64 {
	if x != nil {
		return x.TcpConnect
	}
	return 0
}

func (x *PageLoadEvent) GetRequestStart() int64 {
	if x != nil {
		return x.RequestStart
	}
	return 0
}

func (x *PageLoadEvent) GetResponseStart() int64 {
	if x != nil {
		return x.ResponseStart
	}
	return 0
}

func (x *PageLoadEvent) GetResponseEnd() int64 {
	if x != nil {
		return x.ResponseEnd
	}
	return 0
}

func (x *PageLoadEvent) GetDomInteractive() int64 {
	if x != nil {
		return x.DomInteractive
	}
	return 0
}

func (x *PageLoadEvent) GetDomComplete() int64 {
	if x != nil {
		return x.DomComplete
	}
	return 0
}

func (x *PageLoadEvent) GetLoadComplete() int64 {
	if x != nil {
		return x.LoadComplete
	}
	return 0
}

// Custom event
type CustomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomEvent) Reset() {
	*x = CustomEvent{}
	mi := &file_gosight_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEvent) ProtoMessage() {}

func (x *CustomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEvent.ProtoReflect.Descriptor instead.
func (*CustomEvent) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{9}
}

func (x *CustomEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomEvent) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Replay chunk (rrweb events)
type ReplayChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex      int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TimestampStart  int64                  `protobuf:"varint,2,opt,name=timestamp_start,json=timestampStart,proto3" json:"timestamp_start,omitempty"`
	TimestampEnd    int64                  `protobuf:"varint,3,opt,name=timestamp_end,json=timestampEnd,proto3" json:"timestamp_end,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // Compressed rrweb events JSON
	HasFullSnapshot bool                   `protobuf:"varint,5,opt,name=has_full_snapshot,json=hasFullSnapshot,proto3" json:"has_full_snapshot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplayChunk) Reset() {
	*x = ReplayChunk{}
	mi := &file_gosight_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayChunk) ProtoMessage() {}

func (x *ReplayChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayChunk.ProtoReflect.Descriptor instead.
func (*ReplayChunk) Descriptor() ([]byte, []int) {
	return file_gosight_events_proto_rawDescGZIP(), []int{10}
}

func (x *ReplayChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ReplayChunk) GetTimestampStart() int64 {
	if x != nil {
		return x.TimestampStart
	}
	return 0
}

func (x *ReplayChunk) GetTimestampEnd() int64 {
	if x != nil {
		return x.TimestampEnd
	}
	return 0
}

func (x *ReplayChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReplayChunk) GetHasFullSnapshot() bool {
	if x != nil {
		return x.HasFullSnapshot
	}
	return false
}

var File_gosight_events_proto protoreflect.FileDescriptor

const file_gosight_events_proto_rawDesc = "" +
	"\n" +
	"\x14gosight/events.proto\x12\agosight\x1a\x14gosight/common.proto\"\xaf\x04\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.gosight.EventTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12!\n" +
	"\x04page\x18\x04 \x01(\v2\r.gosight.PageR\x04page\x12+\n" +
	"\x05click\x18\n" +
	" \x01(\v2\x13.gosight.ClickEventH\x00R\x05click\x12.\n" +
	"\x06scroll\x18\v \x01(\v2\x14.gosight.ScrollEventH\x00R\x06scroll\x12+\n" +
	"\x05input\x18\f \x01(\v2\x13.gosight.InputEventH\x00R\x05input\x128\n" +
	"\n" +
	"mouse_move\x18\r \x01(\v2\x17.gosight.MouseMoveEventH\x00R\tmouseMove\x122\n" +
	"\bjs_error\x18\x0e \x01(\v2\x15.gosight.JsErrorEventH\x00R\ajsError\x128\n" +
	"\n" +
	"web_vitals\x18\x0f \x01(\v2\x17.gosight.WebVitalsEventH\x00R\twebVitals\x125\n" +
	"\tpage_load\x18\x10 \x01(\v2\x16.gosight.PageLoadEventH\x00R\bpageLoad\x12.\n" +
	"\x06custom\x18\x11 \x01(\v2\x14.gosight.CustomEventH\x00R\x06customB\t\n" +
	"\apayload\"X\n" +
	"\n" +
	"ClickEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12.\n" +
	"\x06target\x18\x03 \x01(\v2\x16.gosight.TargetElementR\x06target\"\x9f\x01\n" +
	"\vScrollEvent\x12\x1d\n" +
	"\n" +
	"scroll_top\x18\x01 \x01(\x05R\tscrollTop\x12#\n" +
	"\rscroll_height\x18\x02 \x01(\x05R\fscrollHeight\x12'\n" +
	"\x0fviewport_height\x18\x03 \x01(\x05R\x0eviewportHeight\x12#\n" +
	"\rdepth_percent\x18\x04 \x01(\x05R\fdepthPercent\"\x8e\x01\n" +
	"\n" +
	"InputEvent\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x16.gosight.TargetElementR\x06target\x12\x1d\n" +
	"\n" +
	"input_type\x18\x02 \x01(\tR\tinputType\x12\x1b\n" +
	"\tis_masked\x18\x03 \x01(\bR\bisMasked\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"F\n" +
	"\x0eMouseMoveEvent\x124\n" +
	"\tpositions\x18\x01 \x03(\v2\x16.gosight.MousePositionR\tpositions\"9\n" +
	"\rMousePosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01t\x18\x03 \x01(\x03R\x01t\"\xa1\x01\n" +
	"\fJsErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05stack\x18\x02 \x01(\tR\x05stack\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12\x1d\n" +
	"\n" +
	"error_type\x18\x06 \x01(\tR\terrorType\"\xcd\x01\n" +
	"\x0eWebVitalsEvent\x12\x15\n" +
	"\x03lcp\x18\x01 \x01(\x01H\x00R\x03lcp\x88\x01\x01\x12\x15\n" +
	"\x03fid\x18\x02 \x01(\x01H\x01R\x03fid\x88\x01\x01\x12\x15\n" +
	"\x03cls\x18\x03 \x01(\x01H\x02R\x03cls\x88\x01\x01\x12\x17\n" +
	"\x04ttfb\x18\x04 \x01(\x01H\x03R\x04ttfb\x88\x01\x01\x12\x15\n" +
	"\x03fcp\x18\x05 \x01(\x01H\x04R\x03fcp\x88\x01\x01\x12\x15\n" +
	"\x03inp\x18\x06 \x01(\x01H\x05R\x03inp\x88\x01\x01B\x06\n" +
	"\x04_lcpB\x06\n" +
	"\x04_fidB\x06\n" +
	"\x04_clsB\a\n" +
	"\x05_ttfbB\x06\n" +
	"\x04_fcpB\x06\n" +
	"\x04_inp\"\xaf\x02\n" +
	"\rPageLoadEvent\x12\x1d\n" +
	"\n" +
	"dns_lookup\x18\x01 \x01(\x03R\tdnsLookup\x12\x1f\n" +
	"\vtcp_connect\x18\x02 \x01(\x03R\n" +
	"tcpConnect\x12#\n" +
	"\rrequest_start\x18\x03 \x01(\x03R\frequestStart\x12%\n" +
	"\x0eresponse_start\x18\x04 \x01(\x03R\rresponseStart\x12!\n" +
	"\fresponse_end\x18\x05 \x01(\x03R\vresponseEnd\x12'\n" +
	"\x0fdom_interactive\x18\x06 \x01(\x03R\x0edomInteractive\x12!\n" +
	"\fdom_complete\x18\a \x01(\x03R\vdomComplete\x12#\n" +
	"\rload_complete\x18\b \x01(\x03R\floadComplete\"\xa6\x01\n" +
	"\vCustomEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2$.gosight.CustomEvent.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\vReplayChunk\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12'\n" +
	"\x0ftimestamp_start\x18\x02 \x01(\x03R\x0etimestampStart\x12#\n" +
	"\rtimestamp_end\x18\x03 \x01(\x03R\ftimestampEnd\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12*\n" +
	"\x11has_full_snapshot\x18\x05 \x01(\bR\x0fhasFullSnapshot*\xbc\x03\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_TYPE_PAGE_VIEW\x10\x01\x12\x14\n" +
	"\x10EVENT_TYPE_CLICK\x10\x02\x12\x15\n" +
	"\x11EVENT_TYPE_SCROLL\x10\x03\x12\x1b\n" +
	"\x17EVENT_TYPE_INPUT_CHANGE\x10\x04\x12\x1a\n" +
	"\x16EVENT_TYPE_INPUT_FOCUS\x10\x05\x12\x19\n" +
	"\x15EVENT_TYPE_INPUT_BLUR\x10\x06\x12\x19\n" +
	"\x15EVENT_TYPE_MOUSE_MOVE\x10\a\x12 \n" +
	"\x1cEVENT_TYPE_VISIBILITY_CHANGE\x10\b\x12\x17\n" +
	"\x13EVENT_TYPE_JS_ERROR\x10\t\x12\x1c\n" +
	"\x18EVENT_TYPE_NETWORK_ERROR\x10\n" +
	"\x12\x1a\n" +
	"\x16EVENT_TYPE_CONSOLE_LOG\x10\v\x12\x19\n" +
	"\x15EVENT_TYPE_WEB_VITALS\x10\f\x12\x18\n" +
	"\x14EVENT_TYPE_PAGE_LOAD\x10\r\x12\x1c\n" +
	"\x18EVENT_TYPE_RESOURCE_LOAD\x10\x0e\x12\x15\n" +
	"\x11EVENT_TYPE_CUSTOM\x10\x0fB*Z(github.com/gosight/gosight/proto/gosightb\x06proto3"

var (
	file_gosight_events_proto_rawDescOnce sync.Once
	file_gosight_events_proto_rawDescData []byte
)

func file_gosight_events_proto_rawDescGZIP() []byte {
	file_gosight_events_proto_rawDescOnce.Do(func() {
		file_gosight_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gosight_events_proto_rawDesc), len(file_gosight_events_proto_rawDesc)))
	})
	return file_gosight_events_proto_rawDescData
}

var file_gosight_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gosight_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gosight_events_proto_goTypes = []any{
	(EventType)(0),         // 0: gosight.EventType
	(*Event)(nil),          // 1: gosight.Event
	(*ClickEvent)(nil),     // 2: gosight.ClickEvent
	(*ScrollEvent)(nil),    // 3: gosight.ScrollEvent
	(*InputEvent)(nil),     // 4: gosight.InputEvent
	(*MouseMoveEvent)(nil), // 5: gosight.MouseMoveEvent
	(*MousePosition)(nil),  // 6: gosight.MousePosition
	(*JsErrorEvent)(nil),   // 7: gosight.JsErrorEvent
	(*WebVitalsEvent)(nil), // 8: gosight.WebVitalsEvent
	(*PageLoadEvent)(nil),  // 9: gosight.PageLoadEvent
	(*CustomEvent)(nil),    // 10: gosight.CustomEvent
	(*ReplayChunk)(nil),    // 11: gosight.ReplayChunk
	nil,                    // 12: gosight.CustomEvent.PropertiesEntry
	(*Page)(nil),           // 13: gosight.Page
	(*TargetElement)(nil),  // 14: gosight.TargetElement
}
var file_gosight_events_proto_depIdxs = []int32{
	0,  // 0: gosight.Event.type:type_name -> gosight.EventType
	13, // 1: gosight.Event.page:type_name -> gosight.Page
	2,  // 2: gosight.Event.click:type_name -> gosight.ClickEvent
	3,  // 3: gosight.Event.scroll:type_name -> gosight.ScrollEvent
	4,  // 4: gosight.Event.input:type_name -> gosight.InputEvent
	5,  // 5: gosight.Event.mouse_move:type_name -> gosight.MouseMoveEvent
	7,  // 6: gosight.Event.js_error:type_name -> gosight.JsErrorEvent
	8,  // 7: gosight.Event.web_vitals:type_name -> gosight.WebVitalsEvent
	9,  // 8: gosight.Event.page_load:type_name -> gosight.PageLoadEvent
	10, // 9: gosight.Event.custom:type_name -> gosight.CustomEvent
	14, // 10: gosight.ClickEvent.target:type_name -> gosight.TargetElement
	14, // 11: gosight.InputEvent.target:type_name -> gosight.TargetElement
	6,  // 12: gosight.MouseMoveEvent.positions:type_name -> gosight.MousePosition
	12, // 13: gosight.CustomEvent.properties:type_name -> gosight.CustomEvent.PropertiesEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_gosight_events_proto_init() }
func file_gosight_events_proto_init() {
	if File_gosight_events_proto != nil {
		return
	}
	file_gosight_common_proto_init()
	file_gosight_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Click)(nil),
		(*Event_Scroll)(nil),
		(*Event_Input)(nil),
		(*Event_MouseMove)(nil),
		(*Event_JsError)(nil),
		(*Event_WebVitals)(nil),
		(*Event_PageLoad)(nil),
		(*Event_Custom)(nil),
	}
	file_gosight_events_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gosight_events_proto_rawDesc), len(file_gosight_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gosight_events_proto_goTypes,
		DependencyIndexes: file_gosight_events_proto_depIdxs,
		EnumInfos:         file_gosight_events_proto_enumTypes,
		MessageInfos:      file_gosight_events_proto_msgTypes,
	}.Build()
	File_gosight_events_proto = out.File
	file_gosight_events_proto_goTypes = nil
	file_gosight_events_proto_depIdxs = nil
}
