// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: gosight/common.proto

package gosight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Timestamp với millisecond precision
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Millis        int32                  `protobuf:"varint,2,opt,name=millis,proto3" json:"millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_gosight_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_gosight_common_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetMillis() int32 {
	if x != nil {
		return x.Millis
	}
	return 0
}

// Device information
type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Browser        string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion string                 `protobuf:"bytes,2,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	Os             string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion      string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	DeviceType     string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // desktop, mobile, tablet
	ScreenWidth    int32                  `protobuf:"varint,6,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight   int32                  `protobuf:"varint,7,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	ViewportWidth  int32                  `protobuf:"varint,8,opt,name=viewport_width,json=viewportWidth,proto3" json:"viewport_width,omitempty"`
	ViewportHeight int32                  `protobuf:"varint,9,opt,name=viewport_height,json=viewportHeight,proto3" json:"viewport_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_gosight_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_gosight_common_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Device) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *Device) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Device) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Device) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Device) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *Device) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *Device) GetViewportWidth() int32 {
	if x != nil {
		return x.ViewportWidth
	}
	return 0
}

func (x *Device) GetViewportHeight() int32 {
	if x != nil {
		return x.ViewportHeight
	}
	return 0
}

// Page information
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Referrer      string                 `protobuf:"bytes,4,opt,name=referrer,proto3" json:"referrer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_gosight_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_gosight_common_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Page) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

// Session metadata
type SessionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Device        *Device                `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMeta) Reset() {
	*x = SessionMeta{}
	mi := &file_gosight_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMeta) ProtoMessage() {}

func (x *SessionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMeta.ProtoReflect.Descriptor instead.
func (*SessionMeta) Descriptor() ([]byte, []int) {
	return file_gosight_common_proto_rawDescGZIP(), []int{3}
}

func (x *SessionMeta) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMeta) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionMeta) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *SessionMeta) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *SessionMeta) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Click target element
type TargetElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Classes       []string               `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"` // truncated to 100 chars
	Href          string                 `protobuf:"bytes,6,opt,name=href,proto3" json:"href,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetElement) Reset() {
	*x = TargetElement{}
	mi := &file_gosight_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetElement) ProtoMessage() {}

func (x *TargetElement) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetElement.ProtoReflect.Descriptor instead.
func (*TargetElement) Descriptor() ([]byte, []int) {
	return file_gosight_common_proto_rawDescGZIP(), []int{4}
}

func (x *TargetElement) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TargetElement) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *TargetElement) GetClasses() []string {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *TargetElement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TargetElement) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TargetElement) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *TargetElement) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_gosight_common_proto protoreflect.FileDescriptor

const file_gosight_common_proto_rawDesc = "" +
	"\n" +
	"\x14gosight/common.proto\x12\agosight\"=\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x16\n" +
	"\x06millis\x18\x02 \x01(\x05R\x06millis\"\xb3\x02\n" +
	"\x06Device\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12'\n" +
	"\x0fbrowser_version\x18\x02 \x01(\tR\x0ebrowserVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12!\n" +
	"\fscreen_width\x18\x06 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\a \x01(\x05R\fscreenHeight\x12%\n" +
	"\x0eviewport_width\x18\b \x01(\x05R\rviewportWidth\x12'\n" +
	"\x0fviewport_height\x18\t \x01(\x05R\x0eviewportHeight\"^\n" +
	"\x04Page\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\breferrer\x18\x04 \x01(\tR\breferrer\"\xa6\x01\n" +
	"\vSessionMeta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x06device\x18\x03 \x01(\v2\x0f.gosight.DeviceR\x06device\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\x96\x02\n" +
	"\rTargetElement\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x18\n" +
	"\aclasses\x18\x03 \x03(\tR\aclasses\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x12\n" +
	"\x04href\x18\x06 \x01(\tR\x04href\x12F\n" +
	"\n" +
	"attributes\x18\a \x03(\v2&.gosight.TargetElement.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B*Z(github.com/gosight/gosight/proto/gosightb\x06proto3"

var (
	file_gosight_common_proto_rawDescOnce sync.Once
	file_gosight_common_proto_rawDescData []byte
)

func file_gosight_common_proto_rawDescGZIP() []byte {
	file_gosight_common_proto_rawDescOnce.Do(func() {
		file_gosight_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gosight_common_proto_rawDesc), len(file_gosight_common_proto_rawDesc)))
	})
	return file_gosight_common_proto_rawDescData
}

var file_gosight_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gosight_common_proto_goTypes = []any{
	(*Timestamp)(nil),     // 0: gosight.Timestamp
	(*Device)(nil),        // 1: gosight.Device
	(*Page)(nil),          // 2: gosight.Page
	(*SessionMeta)(nil),   // 3: gosight.SessionMeta
	(*TargetElement)(nil), // 4: gosight.TargetElement
	nil,                   // 5: gosight.TargetElement.AttributesEntry
}
var file_gosight_common_proto_depIdxs = []int32{
	1, // 0: gosight.SessionMeta.device:type_name -> gosight.Device
	5, // 1: gosight.TargetElement.attributes:type_name -> gosight.TargetElement.AttributesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gosight_common_proto_init() }
func file_gosight_common_proto_init() {
	if File_gosight_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gosight_common_proto_rawDesc), len(file_gosight_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gosight_common_proto_goTypes,
		DependencyIndexes: file_gosight_common_proto_depIdxs,
		MessageInfos:      file_gosight_common_proto_msgTypes,
	}.Build()
	File_gosight_common_proto = out.File
	file_gosight_common_proto_goTypes = nil
	file_gosight_common_proto_depIdxs = nil
}
