// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.4
// source: gosight/ingest.proto

package gosight

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestService_SendEvents_FullMethodName = "/gosight.IngestService/SendEvents"
	IngestService_SendReplay_FullMethodName = "/gosight.IngestService/SendReplay"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ingest service
type IngestServiceClient interface {
	// Stream events from client
	SendEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, EventAck], error)
	// Send replay chunks
	SendReplay(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReplayChunk, ReplayAck], error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) SendEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, EventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[0], IngestService_SendEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBatch, EventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_SendEventsClient = grpc.BidiStreamingClient[EventBatch, EventAck]

func (c *ingestServiceClient) SendReplay(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReplayChunk, ReplayAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[1], IngestService_SendReplay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplayChunk, ReplayAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_SendReplayClient = grpc.ClientStreamingClient[ReplayChunk, ReplayAck]

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// Ingest service
type IngestServiceServer interface {
	// Stream events from client
	SendEvents(grpc.BidiStreamingServer[EventBatch, EventAck]) error
	// Send replay chunks
	SendReplay(grpc.ClientStreamingServer[ReplayChunk, ReplayAck]) error
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) SendEvents(grpc.BidiStreamingServer[EventBatch, EventAck]) error {
	return status.Error(codes.Unimplemented, "method SendEvents not implemented")
}
func (UnimplementedIngestServiceServer) SendReplay(grpc.ClientStreamingServer[ReplayChunk, ReplayAck]) error {
	return status.Error(codes.Unimplemented, "method SendReplay not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_SendEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).SendEvents(&grpc.GenericServerStream[EventBatch, EventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_SendEventsServer = grpc.BidiStreamingServer[EventBatch, EventAck]

func _IngestService_SendReplay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).SendReplay(&grpc.GenericServerStream[ReplayChunk, ReplayAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_SendReplayServer = grpc.ClientStreamingServer[ReplayChunk, ReplayAck]

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gosight.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendEvents",
			Handler:       _IngestService_SendEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendReplay",
			Handler:       _IngestService_SendReplay_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "gosight/ingest.proto",
}
