// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: gosight/ingest.proto

package gosight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Batch of events
type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectKey    string                 `protobuf:"bytes,1,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
	Session       *SessionMeta           `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	SentAt        int64                  `protobuf:"varint,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_gosight_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_gosight_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *EventBatch) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *EventBatch) GetSession() *SessionMeta {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

// Event acknowledgment
type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,2,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int32                  `protobuf:"varint,3,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_gosight_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_gosight_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *EventAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EventAck) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *EventAck) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *EventAck) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Replay acknowledgment
type ReplayAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayAck) Reset() {
	*x = ReplayAck{}
	mi := &file_gosight_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayAck) ProtoMessage() {}

func (x *ReplayAck) ProtoReflect() protoreflect.Message {
	mi := &file_gosight_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayAck.ProtoReflect.Descriptor instead.
func (*ReplayAck) Descriptor() ([]byte, []int) {
	return file_gosight_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *ReplayAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplayAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gosight_ingest_proto protoreflect.FileDescriptor

const file_gosight_ingest_proto_rawDesc = "" +
	"\n" +
	"\x14gosight/ingest.proto\x12\agosight\x1a\x14gosight/common.proto\x1a\x14gosight/events.proto\"\x9e\x01\n" +
	"\n" +
	"EventBatch\x12\x1f\n" +
	"\vproject_key\x18\x01 \x01(\tR\n" +
	"projectKey\x12.\n" +
	"\asession\x18\x02 \x01(\v2\x14.gosight.SessionMetaR\asession\x12&\n" +
	"\x06events\x18\x03 \x03(\v2\x0e.gosight.EventR\x06events\x12\x17\n" +
	"\asent_at\x18\x04 \x01(\x03R\x06sentAt\"\x8a\x01\n" +
	"\bEventAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eaccepted_count\x18\x02 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x03 \x01(\x05R\rrejectedCount\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"?\n" +
	"\tReplayAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x83\x01\n" +
	"\rIngestService\x128\n" +
	"\n" +
	"SendEvents\x12\x13.gosight.EventBatch\x1a\x11.gosight.EventAck(\x010\x01\x128\n" +
	"\n" +
	"SendReplay\x12\x14.gosight.ReplayChunk\x1a\x12.gosight.ReplayAck(\x01B*Z(github.com/gosight/gosight/proto/gosightb\x06proto3"

var (
	file_gosight_ingest_proto_rawDescOnce sync.Once
	file_gosight_ingest_proto_rawDescData []byte
)

func file_gosight_ingest_proto_rawDescGZIP() []byte {
	file_gosight_ingest_proto_rawDescOnce.Do(func() {
		file_gosight_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gosight_ingest_proto_rawDesc), len(file_gosight_ingest_proto_rawDesc)))
	})
	return file_gosight_ingest_proto_rawDescData
}

var file_gosight_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gosight_ingest_proto_goTypes = []any{
	(*EventBatch)(nil),  // 0: gosight.EventBatch
	(*EventAck)(nil),    // 1: gosight.EventAck
	(*ReplayAck)(nil),   // 2: gosight.ReplayAck
	(*SessionMeta)(nil), // 3: gosight.SessionMeta
	(*Event)(nil),       // 4: gosight.Event
	(*ReplayChunk)(nil), // 5: gosight.ReplayChunk
}
var file_gosight_ingest_proto_depIdxs = []int32{
	3, // 0: gosight.EventBatch.session:type_name -> gosight.SessionMeta
	4, // 1: gosight.EventBatch.events:type_name -> gosight.Event
	0, // 2: gosight.IngestService.SendEvents:input_type -> gosight.EventBatch
	5, // 3: gosight.IngestService.SendReplay:input_type -> gosight.ReplayChunk
	1, // 4: gosight.IngestService.SendEvents:output_type -> gosight.EventAck
	2, // 5: gosight.IngestService.SendReplay:output_type -> gosight.ReplayAck
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gosight_ingest_proto_init() }
func file_gosight_ingest_proto_init() {
	if File_gosight_ingest_proto != nil {
		return
	}
	file_gosight_common_proto_init()
	file_gosight_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gosight_ingest_proto_rawDesc), len(file_gosight_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gosight_ingest_proto_goTypes,
		DependencyIndexes: file_gosight_ingest_proto_depIdxs,
		MessageInfos:      file_gosight_ingest_proto_msgTypes,
	}.Build()
	File_gosight_ingest_proto = out.File
	file_gosight_ingest_proto_goTypes = nil
	file_gosight_ingest_proto_depIdxs = nil
}
